### PR TITLE
API fixes, logging and enhanced csv export

### PR DESCRIPTION
**Pull request by visika**
My work is mainly in the last commit, the others are already known.

### CODE REVIEW

**Comment by ofirpeer** [comment]
Tried your version, but got the following error:
```
WWapApi.js:56 Uncaught (in promise) TypeError: window.webpackJsonp is not a function
    at readMore (WWapApi.js:56)
```
referring to this line:
```
const WLAPWAPStore = window.webpackJsonp([], null , [funcName1]).default;
```
and indeed it's an array. 
Do you know how to fix that?

**Comment by visika** [comment]
My first guess is the api of whatsapp web changed again and everything is broken. I'm really no expert at this, I tinkered a bit and got it working through trial and error by a miracle. And still it didn't track statuses reliably. 
I'm sorry.

**Comment by ofirpeer** [comment]
Here I thing it has something to do with webpack versions and not the api.
but thanks anyway

**Comment by ricardoperovano** [comment]
Hey Guys, I have the fix, I'll bring that in a moment for you

**Comment by ofirpeer** [comment]
Awesome!!
Are you adding it to your repo?

**Pull request closed without merging**
